FROM ubuntu:xenial
MAINTAINER Marcel Grossmann <whatever4711@gmail.com>
LABEL architecture="amd64"

ENV dir /src
RUN apt-get update && \
    apt-get install -y \
    make \
    git \
    texlive-base \
    texlive-latex-extra \
    texlive-lang-german \
    gnuplot \
    latexmk \
    texlive-math-extra \
    texlive-fonts-extra \
    texlive-generic-extra \
    texlive-science \
    texlive-xetex && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR ${dir}
